services:
  postgres:
    image: postgres:18
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 1s
      retries: 5
    ports:
      - 6000:5432
    volumes:
      - pgdata:/var/lib/postgresql
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push

  migration:
    image: migrate/migrate
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: ["-path", "/migrations", "-database", "${DATABASE_URI}", "up"]
    volumes:
      - ./migrations:/migrations
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push

  server:
    env_file:
      - .env
    build:
      dockerfile: ./images/server.Dockerfile
      context: .
    ports:
      - 8080:8080
    depends_on:
      migration:
        condition: service_completed_successfully
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push

volumes:
  pgdata:
